### ISSUE TITLE
Volunteer | Want to join the initiative.

### ISSUE THREAD

**Issue by NishkarshRaj** [Codess-Cafe/Daily-DSA-Bot#1]
@ShreyaPrasad1209 can I join this amazing initiative? 💯

**Comment by ShreyaPrasad1209** [comment]
@devaar100 can he join? He's Principal DevOps Evangelist and Consultant for StatusNeo Inc. and a GitHub Star ⭐ . I feel he could contribute a great deal to the community 🚀

**Comment by devaar100** [comment]
@ShreyaPrasad1209 yeah definitely 🙂
Welcome @NishkarshRaj ! It's great to have you here with us.
